import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import NavBar from "@/components/shared/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        position:"relative",
        height:"max-screen"
      }}>
        <nav className="p-6 fixed top-0 left-0 h-auto w-full z-30">
          <NavBar />
        </nav>
        {children}
        <footer className="absolute bottom-0 left-0 w-full mt-[40px] h-[50px]">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
